const actionTypes = Object.freeze({
  APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
  SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

  ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',

  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
  PROCESS_LOGOUT: 'PROCESS_LOGOUT',

  //
  FETCH_GENDER_START: 'FETCH_GENDER_START',
  FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
  FETCH_GENDER_FAILDED: 'FETCH_GENDER_FAILDED',

  FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
  FETCH_POSITION_FAILDED: 'FETCH_POSITION_FAILDED',

  FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
  FETCH_ROLE_FAILDED: 'FETCH_ROLE_FAILDED',

  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_FAILDED: 'CREATE_USER_FAILDED',

  EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
  EDIT_USER_FAILDED: 'EDIT_USER_FAILDED',

  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_FAILDED: 'DELETE_USER_FAILDED',

  FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
  FETCH_ALL_USERS_FAILDED: 'FETCH_ALL_USERS_FAILDED',

  FETCH_TOP_DOCTORS_SUCCESS: 'FETCH_TOP_DOCTORS_SUCCESS',
  FETCH_TOP_DOCTORS_FAILDED: 'FETCH_TOP_DOCTORS_FAILDED',

  FETCH_ALL_DOCTORS_SUCCESS: 'FETCH_ALL_DOCTORS_SUCCESS',
  FETCH_ALL_DOCTORS_FAILDED: 'FETCH_ALL_DOCTORS_FAILDED',

  SAVE_DETAIL_DOCTOR_SUCCESS: 'SAVE_DETAIL_DOCTOR_SUCCESS',
  SAVE_DETAIL_DOCTOR_FAILDED: 'SAVE_DETAIL_DOCTOR_FAILDED',

  FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS: 'FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS',
  FETCH_ALLCODE_SCHEDULE_TIME_FAILDED: 'FETCH_ALLCODE_SCHEDULE_TIME_FAILDED',

  FETCH_REQUIRED_DOCTOR_INFOR_START: 'FETCH_REQUIRED_DOCTOR_INFOR_START',
  FETCH_REQUIRED_DOCTOR_INFOR_SUCCESS: 'FETCH_REQUIRED_DOCTOR_INFOR_SUCCESS',
  FETCH_REQUIRED_DOCTOR_INFOR_FAILDED: 'FETCH_REQUIRED_DOCTOR_INFOR_FAILDED',

  CREATE_HANDBOOK_SUCCESS: 'CREATE_HANDBOOK_SUCCESS',
  CREATE_HANDBOOK_FAILDED: 'CREATE_HANDBOOK_FAILDED',

  EDIT_HANDBOOK_SUCCESS: 'EDIT_HANDBOOK_SUCCESS',
  EDIT_HANDBOOK_FAILDED: 'EDIT_HANDBOOK_FAILDED',

  DELETE_HANDBOOK_SUCCESS: 'DELETE_HANDBOOK_SUCCESS',
  DELETE_HANDBOOK_FAILDED: 'DELETE_HANDBOOK_FAILDED',

  FETCH_ALL_HANDBOOKS_SUCCESS: 'FETCH_ALL_HANDBOOKS_SUCCESS',
  FETCH_ALL_HANDBOOKS_FAILDED: 'FETCH_ALL_HANDBOOKS_FAILDED',

  CREATE_SPECIALTY_SUCCESS: 'CREATE_SPECIALTY_SUCCESS',
  CREATE_SPECIALTY_FAILDED: 'CREATE_SPECIALTY_FAILDED',

  EDIT_SPECIALTY_SUCCESS: 'EDIT_SPECIALTY_SUCCESS',
  EDIT_SPECIALTY_FAILDED: 'EDIT_SPECIALTY_FAILDED',

  DELETE_SPECIALTY_SUCCESS: 'DELETE_SPECIALTY_SUCCESS',
  DELETE_SPECIALTY_FAILDED: 'DELETE_SPECIALTY_FAILDED',

  FETCH_ALL_SPECIALTIES_SUCCESS: 'FETCH_ALL_SPECIALTIES_SUCCESS',
  FETCH_ALL_SPECIALTIES_FAILDED: 'FETCH_ALL_SPECIALTIES_FAILDED',
  ADD_SPECIALTY_SUCCESS: 'ADD_SPECIALTY_SUCCESS',

  CREATE_CLINIC_SUCCESS: 'CREATE_CLINIC_SUCCESS',
  CREATE_CLINIC_FAILDED: 'CREATE_CLINIC_FAILDED',

  EDIT_CLINIC_SUCCESS: 'EDIT_CLINIC_SUCCESS',
  EDIT_CLINIC_FAILDED: 'EDIT_CLINIC_FAILDED',

  DELETE_CLINIC_SUCCESS: 'DELETE_CLINIC_SUCCESS',
  DELETE_CLINIC_FAILDED: 'DELETE_CLINIC_FAILDED',

  FETCH_ALL_CLINICS_SUCCESS: 'FETCH_ALL_CLINICS_SUCCESS',
  FETCH_ALL_CLINICS_FAILDED: 'FETCH_ALL_CLINICS_FAILDED',
  ADD_CLINIC_SUCCESS: 'ADD_CLINIC_SUCCESS',

  FETCH_PostOfCategory_FAILDED: 'FETCH_PostOfCategory_FAILDED',
  FETCH_PostOfCategory_SUCCESS: 'FETCH_PostOfCategory_SUCCESS',

  FETCH_ALL_MEDICAL_PACKAGES_SUCCESS: 'FETCH_ALL_MEDICAL_PACKAGES_SUCCESS',
  FETCH_ALL_MEDICAL_PACKAGES_FAILDED: 'FETCH_ALL_MEDICAL_PACKAGES_FAILDED',

  DELETE_MEDICAL_PACKAGE_SUCCESS: 'DELETE_MEDICAL_PACKAGE_SUCCESS',
  DELETE_MEDICAL_PACKAGE_FAILDED: 'DELETE_MEDICAL_PACKAGE_FAILDED',

  FETCH_ALL_MEDICAL_PACKAGE_SUCCESS: 'FETCH_ALL_MEDICAL_PACKAGE_SUCCESS',
  CREATE_MEDICAL_PACKAGE_SUCCESS: 'CREATE_MEDICAL_PACKAGE_SUCCESS',

  FETCH_CLINIC_START: 'FETCH_CLINIC_START',
  FETCH_CLINIC_SUCCESS: 'FETCH_CLINIC_SUCCESS',
  FETCH_CLINIC_FAILED: 'FETCH_CLINIC_FAILED',

  FETCH_SPECIALTY_START: 'FETCH_SPECIALTY_START',
  FETCH_SPECIALTY_SUCCESS: 'FETCH_SPECIALTY_SUCCESS',
  FETCH_SPECIALTY_FAILED: 'FETCH_SPECIALTY_FAILED',
});

export default actionTypes;
